### PR TITLE
Split into library and thin CLI wrapper

### PR DESCRIPTION
**Pull request by emlun**
Hi! I recently found this after I started working on a [map analyzer toy project](https://github.com/emlun/spire-map-gui), and thought it'd be neat if I could use this as a library to generate the map from a given seed. Unfortunately, right now all the code is in the binary module, so it can't really be used as a library.

This series of changes restructures the code a bit, mainly splitting it into a core library module and a thin CLI wrapper. I've also restructured a few of the top-level functions into primarily returning data, and split out the print statements into separate functions. This enabled me to do [stuff like this](https://emlun.se/spire-map-gui/?seed=0:-4441084313101682968), which uses this project as a WebAssembly library to generate the map.

Would you like this?

### CODE REVIEW

**Comment by emlun** [comment]
(I recommend viewing the diffs one commit at a time, since most of the diff volume is a simple file rename which gets properly de-noised one commit at a time but not when taken all together.)

**Comment by Ru5ty0ne** [comment]
It will be very handy that people now can use it as library. Thank you for attention and your time investment =)

**Comment by emlun** [comment]
Cool, glad you like it! I have some more additions as well, if you want them. Most importantly a couple of unit tests and a small change to make it compatible with stable Rust (and not require Nightly). Would you like a pull request with that too?

**Comment by Ru5ty0ne** [comment]
Sure, make a PR and I will merge it.

**Comment by emlun** [comment]
Alright :smile: here you go:

- The most important parts: #2
- Some refactorings I believe won't be very controversial: #3 
- And lastly, some things that are not important and definitely down to personal taste: #4

**Pull request merged**
